### ISSUE TITLE
Log file: do you actually need to fdatasync() after every write?

### ISSUE THREAD

**Issue by nbarrientos** [rhboot/grubby#10]
```
# time ./grubby --default-kernel
/boot/vmlinuz-3.10.0-229.20.1.el7.x86_64

real    0m0.151s
user    0m0.006s
sys     0m0.010s
# time grubby --default-kernel
/boot/vmlinuz-3.10.0-229.20.1.el7.x86_64

real    0m12.558s
user    0m0.005s
sys     0m0.022s
# git diff
diff --git a/log.c b/log.c
index 2bcfa40..1e82a9e 100644
--- a/log.c
+++ b/log.c
@@ -101,7 +101,7 @@ log_vmessage(FILE *log, const char *msg, va_list ap)

        vfprintf(log ? log : f, msg, aq);
        va_end(aq);
-       fdatasync(log ? fileno(log) : log_fd);
+       //fdatasync(log ? fileno(log) : log_fd);

        return 0;
 }
```

Thanks.

**Comment by nbarrientos** [comment]
```
# rpm -qi grubby
Name        : grubby
Version     : 8.28
Release     : 11.el7
Architecture: x86_64
Install Date: Fri 10 Apr 2015 01:29:21 CEST
Group       : System Environment/Base
Size        : 118683
License     : GPLv2+
Signature   : RSA/SHA256, Sat 14 Mar 2015 08:54:15 CET, Key ID 24c6a8a7f4a80eb5
Source RPM  : grubby-8.28-11.el7.src.rpm
Build Date  : Fri 06 Mar 2015 01:30:41 CET
Build Host  : worker1.bsys.centos.org
Relocations : (not relocatable)
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Vendor      : CentOS
URL         : http://git.fedorahosted.org/git/grubby.git
Summary     : Command line tool for updating bootloader configs
Description :
grubby  is  a command line tool for updating and displaying information about
the configuration files for the grub, lilo, elilo (ia64),  yaboot (powerpc)
and zipl (s390) boot loaders. It is primarily designed to be used from scripts
which install new kernels and need to find information about the current boot
environment.
```

**Comment by wenjianhn** [comment]
It does so for buffers of which length are less than 10 bytes...

> open("/var/log/grubby", O_RDWR|O_CREAT|O_APPEND|O_CLOEXEC, 0600) = 3
...
write(3, "DBG: 3406: Fri Nov 20 00:36:33 2"..., 37) = 37
fdatasync(3)                            = 0
write(3, "command line: --default-kernel\n", 31) = 31
fdatasync(3)                            = 0
write(3, "DBG: Image entry succeeded: ", 28) = 28
fdatasync(3)                            = 0
write(3, "\n", 1)                       = 1
fdatasync(3)                            = 0
write(3, "DBG: ", 5)                    = 5
fdatasync(3)                            = 0
write(3, "menuentry ", 10)              = 10
fdatasync(3)                            = 0
write(3, "'Oracle Linux Server 7.6, with U"..., 91) = 91
fdatasync(3)                            = 0 
write(3, " ", 1)                        = 1 
fdatasync(3)                            = 0
write(3, "--class oracle --class gnu-linux"..., 181) = 181
fdatasync(3)                            = 0
write(3, "\n", 1)                       = 1             
fdatasync(3)                            = 0
write(3, "DBG: \t", 6)                  = 6
fdatasync(3)                            = 0
write(3, "load_video", 10)              = 10
fdatasync(3)                            = 0             
write(3, "\n", 1)                       = 1
fdatasync(3)                            = 0
write(3, "DBG: \t", 6)                  = 6
fdatasync(3)                            = 0
write(3, "set ", 4)                     = 4
fdatasync(3)                            = 0
write(3, "gfxpayload=", 11)             = 11
fdatasync(3)                            = 0
write(3, "keep", 4)                     = 4
fdatasync(3)                            = 0
write(3, "\n", 1)                       = 1
fdatasync(3)                            = 0
write(3, "DBG: \t", 6)                  = 6
fdatasync(3)                            = 0
write(3, "insmod ", 7)                  = 7
...

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
