### ISSUE TITLE
BUG: Missing `fclose` in `writeConfig`.

### ISSUE THREAD

**Issue by jasonvmiller** [rhboot/grubby#12]
There is no `fclose` call at the end of `writeConfig` in the case the file is being written somewhere other than stdout, which can cause `rename` to get issued before the `write` call, ultimately resulting in an empty configuration file moved into place in some cases.

**Comment by fcami** [comment]
Fixed since d9406b061cef40bd42ed813e13bd02b3a285adae - @jasonvmiller could you check if the code suits you now?

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
