### ISSUE TITLE
[RFE] Grubby filter --info= --initrd=

### ISSUE THREAD

**Issue by jcpunk** [rhboot/grubby#18]
I'm inserting a few rescue iso images into my boot environment using MEMDISK from syslinux.

At this time grubby doesn't allow me an easy way to filter by initrd and kernel.

Example
```
# grubby --info=/boot/memdisk 
index=0
kernel=/boot/memdisk
args="iso"
initrd=/boot/pxefallback.iso
title=CAUTION - REINSTALL SYSTEM
index=4
kernel=/boot/memdisk
initrd=/boot/freedos.img
title=Boot to FreeDOS (for DOS firmware updates)

# grubby --info=/boot/memdisk --initrd=/boot/freedos.img
grubby: kernel path expected
```

Being able to filter for just the image I'm looking for feels like the intent of `--info` this RFE would help extend it for my use case.

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
