### ISSUE TITLE
new-kernel-pkg: Add --dracutoptions

### ISSUE THREAD

**Issue by prarit** [rhboot/grubby#29]
I want to create an initramfs using xz compression but there is no way to do that from new-kernel-pkg.  I have to manually edit new-kernel-pkg with '--xz' and then call new-kernel-pkg.

Add --dracutoptions which is a list of options that will be added to the dracut command line.

**Comment by prarit** [comment]
I am testing a patch and will attach it to this issue shortly.

**Comment by prarit** [comment]
Modifying the kernel rpm with --dracutoptions="--xz" results in

[root@intel-purley-03 boot]# ls -ltr initramfs-* | grep -v kdump | grep -v rescue
-rw-------. 1 root root 21771110 Jan  3 07:38 initramfs-3.10.0-826.el7.x86_64.img
-rw-------. 1 root root 21119240 Jan  4 11:39 initramfs-3.10.0-826.el7gzip.x86_64.img  <<< normal gzip
-rw-------. 1 root root 16469280 Jan  4 12:19 initramfs-3.10.0-826.el7xz.x86_64.img <<< xz

The savings with Fedora are approximately the same.
P.

**Comment by prarit** [comment]
[0001-new-kernel-pkg-Add-dracutoptions.txt](https://github.com/rhboot/grubby/files/1604598/0001-new-kernel-pkg-Add-dracutoptions.txt)

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
