### ISSUE TITLE
Document return values in man page

### ISSUE THREAD

**Issue by altmind** [rhboot/grubby#33]
Knowing return values is very important for automation.
Manual page of grubby(in centos 7.4, v 23.el7) dont mention what are the return values.

Can you please extend the man page?

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
