### ISSUE TITLE
Btrfs, mounted top level results in bogus initrd prefix, boot failure

### ISSUE THREAD

**Issue by cmurf** [rhboot/grubby#34]
The recent Btrfs subvolume change has a problem.

Summary:
rootfs is on subvolume `root`, and /boot is a directory in it. The correct grub2-mkconfig entries use prefix`/root/boot/`
But grubby occasionally uses prefix `//boot/` only for the initrdefi line, the linuxefi line remains `/root/boot/` and the result is on reboot GRUB can't find the initramfs, and boot fails.

The problem happens only when the top level of the file system is mounted. For example:

Does not happen:
```
[chris@f28s ~]$ cat /proc/mounts | grep btrfs
/dev/sda1 / btrfs rw,seclabel,noatime,compress=zstd,space_cache=v2,subvolid=325,subvol=/root 0 0
/dev/sda1 /var/lib/libvirt/images btrfs rw,seclabel,relatime,compress=zstd,space_cache=v2,subvolid=350,subvol=/libvirtimages 0 0
```

Does happen:
```
[chris@f28s ~]$ cat /proc/mounts | grep btrfs
/dev/sda1 / btrfs rw,seclabel,noatime,compress=zstd,space_cache=v2,subvolid=325,subvol=/root 0 0
/dev/sda1 /var/lib/libvirt/images btrfs rw,seclabel,relatime,compress=zstd,space_cache=v2,subvolid=350,subvol=/libvirtimages 0 0
/dev/sda1 /mnt/int btrfs rw,seclabel,relatime,compress=zstd,space_cache=v2,subvolid=5,subvol=/ 0 0
```

grub2-mkconfig doesn't make this mistake.

grubby modified grub.cfg exhibting the problem in the first menu entry
[grubby_grub.txt](https://github.com/rhboot/grubby/files/1957359/grubby_grub.txt)

strace grubby (new-kernel-pkg runs grubby twice, the problem happens with the 2nd command that uses --update-kernel and --initrd flags)
[strace grubby update initrd.txt](https://github.com/rhboot/grubby/files/1957360/strace.grubby.update.initrd.txt)

**Comment by cmurf** [comment]
This problem happens when a separate subvolume is mounted at /boot as well, e.g. fstab option subvol=boot mounting at /boot

        linuxefi /boot/vmlinuz-4.16.4-300.fc28.x86_64 root=UUID=e79777de-5a8b-4fea-a2ed-e44971eecc60 ro rootflags=subvol=root elevator=deadline zswap.enabled=1 LANG=en_US.UTF-8
        initrdefi //initramfs-4.16.4-300.fc28.x86_64

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
