### ISSUE TITLE
Enhancement - Support for setting/clearing `--unrestricted` from menu entries

### ISSUE THREAD

**Issue by jflemer-ndp** [rhboot/grubby#44]
I do not see anyway in grubby to set or clear the `--unrestricted` in a `menuentry`. It seems that when using `--copy-default`, the current default kernel value is copied. Without using `--copy-default` then `--unrestricted` is omitted. (Note, I am using version 8.28 at the moment, but looked at latest in git also.)

Request an option to allow setting/removing this flag from existing and new menu entries.

https://github.com/rhboot/grubby/blob/526e39e42f6501d5aed886f9b12b712dcb9cecf6/grubby.c#L3448

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
