### ISSUE TITLE
grubby does not find kernel images on btrfs subvolumes 

### ISSUE THREAD

**Issue by bllngr** [rhboot/grubby#45]
**Description of problem:**

Config files created for/by BootLoaderSpec contain verbose paths to kernel images containing the whole btrfs subvolume paths, while the kernel images are accessible from the mounted path in the running system:

    # ls /boot/vmlinuz-5.0.16-300.fc30.x86_64 
    /boot/vmlinuz-5.0.16-300.fc30.x86_64

    
    # head -4 /boot/loader/entries/76c448f84ac94df9b7354b30c92fb8eb-5.0.16-300.fc30.x86_64.conf 
    title Fedora (5.0.16-300.fc30.x86_64) 30 (Thirty)
    version 5.0.16-300.fc30.x86_64
    linux /root/boot/vmlinuz-5.0.16-300.fc30.x86_64
    initrd /root/boot/initramfs-5.0.16-300.fc30.x86_64.img
           ^^^^^^^^^^^

This results in incomprehensible error messages when using grubby:

    grubby --info /boot/vmlinuz-5.0.14-300.fc30.x86_64
    The param /boot/vmlinuz-5.0.14-300.fc30.x86_64 is incorrect

It seems like it's actually not possible at all to use grubby --update-kernel, even with the full path:

    grubby --update-kernel /root/boot/vmlinuz-5.0.14-300.fc30.x86_64 
    The param /boot/vmlinuz-5.0.14-300.fc30.x86_64 is incorrect

**Version-Release number of selected component (if applicable):**
```
grub2-common.noarch          1:2.02-80.fc30                 @updates                       
grubby.x86_64                8.40-30.fc30                   @fedora  
```

**How reproducible:**
Always, when the partition containing `/boot` is mounted from a btrfs subvolume

**Expected results:**
Accessing kernel images via grubby should work when accessing them from the running system's path (/boot instead of /root/boot).

**Additional info:**

    sudo btrfs subvolume list /
    ID 258 gen 1087767 top level 5 path home
    ID 320 gen 1087767 top level 5 path root

**Comment by bllngr** [comment]
**Note:** This has also been reported to the Fedora Bugzilla at https://bugzilla.redhat.com/show_bug.cgi?id=1711540

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
