### ISSUE TITLE
/sbin/installkernel doesn't update default grub kernel

### ISSUE THREAD

**Issue by hadess** [rhboot/grubby#46]
The `make rpm` target (now `make rpm-pkg` target) in the kernel used to create an RPM package that, when installed, would become the new default selection in the grub menu.

The code currently in the kernel doesn't do that anymore:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/scripts/package/mkspec#n110

Installing this kernel should make it the default entry in grub.

(tested on Fedora 30 with the current tip of the linus git kernel)

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
