### ISSUE TITLE
stray symlinks in /boot ($LINK_PATH)

### ISSUE THREAD

**Issue by stellarhopper** [rhboot/grubby#48]
When installing a kernel with the INSTALL_PATH variable set to install to a specific location, `installkernel-bls` still tries to setup symlinks to vmlinux and System.map in `/boot.`

I'm curious as to the rationale for these symlinks - it seems to me they should also obey the INSTALL_PATH variable if set.

The relevant lines are:
```
ln -fs ${RELATIVE_PATH}$INSTALL_PATH/$KERNEL_NAME-$KERNEL_VERSION $LINK_PATH/$KERNEL_NAME
ln -fs ${RELATIVE_PATH}$INSTALL_PATH/System.map-$KERNEL_VERSION $LINK_PATH/System.map
```

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
