### ISSUE TITLE
In the /etc/mtab file, when the root point position is greater than 4K, Grubby will error

### ISSUE THREAD

**Issue by LikrOvO** [rhboot/grubby#49]
1、create multiple mount points and the /etc/mtab file exceeds 4K
2、create a rootbak partition and mount it (with the operating system in the partition), chroot to the rootbak partition, and upgrade the kernel
Error：grubby fatal error： unable to find a suitable temolate。
The grub.cfg file was not successfully updated。

**Comment by liquor1110** [comment]
[root@localhost ~]# rm /etc/mtab
rm: remove symbolic link '/etc/mtab'? y
[root@localhost ~]# cp /proc/mounts /etc/mtab
[root@localhost ~]# ls -l --block-size=K /etc/mtab
-r--------. 1 root root 3K Jul 14 11:09 /etc/mtab
[root@localhost ~]# cp /boot/grub2/grub.cfg /tmp/grub.test.cfg
[root@localhost ~]# cat -n /etc/mtab | grep root
    25	/dev/mapper/openeuler-root / ext4 rw,seclabel,relatime 0 0
[root@localhost ~]# vim test.sh
[root@localhost ~]# cat test.sh 
size=$1
while true
do
	sed -i '24 a tmpfs /tmp/test-aaaaaaaaaaaaaaa tmppfs rw,relatime,size=1024k 0 0' /etc/mtab
        tmp=$(ls -l --block-size=K /etc/mtab | grep -Po '\d*(?=K)')
        if [[ $tmp -ge $size ]]; then
                break
        fi
done
[root@localhost ~]# sh test.sh 70
[root@localhost ~]# ls -l --block-size=K /etc/mtab
-r--------. 1 root root 70K Jul 14 11:31 /etc/mtab
[root@localhost ~]# cat -n /etc/mtab | grep root
  1055	/dev/mapper/openeuler-root / ext4 rw,seclabel,relatime 0 0
[root@localhost ~]# grubby -c /tmp/grub.test.cfg --add-kernel=test_kernel --title=test_title --copy-default
grubby fatal error: unable to find a suitable template
[root@localhost ~]#

**Comment by liquor1110** [comment]
Because the /proc file system scenario is difficult to create, regular file systems are used for replication

**Comment by liquor1110** [comment]
https://github.com/rhboot/grubby/blob/master/grubby.c#L1978
The buffer size is 64K, so use the normal file system to reproduce the error, 64K being the triggered boundary

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
