### ISSUE TITLE
test/grub2.15 Fail in aarch64

### ISSUE THREAD

**Issue by yangmingtai** [rhboot/grubby#53]
Fedora grubby.spec
%ifnarch aarch64 %{arm}
%check
make test
%endif

I must make check in aarch64, how can i do?

**Comment by yangmingtai** [comment]
GRUB2 add kernel ... --grub2 test/grub2.15 test/results/add/g2-1.15
-------------------------------------------------------------
FAIL: ./grubby --grub2 --bad-image-okay --env=test/grub2-support_files/env_temp -c test/grub2.15 -o - --add-kernel=/boot/vmlinuz-0-rescue-5a94251776a14678911d4ae0949500f5 --initrd /boot/initramfs-0-rescue-5a94251776a14678911d4ae0949500f5.img --copy-default --title Fedora\ 21\ Rescue --args=root=/fooooo --remove-kernel=wtf --boot-filesystem=/boot/ --efi
--- test/results/add/g2-1.15    2015-04-15 19:37:58.000000000 +0000
+++ -   2021-02-20 05:09:23.771586720 +0000
@@ -55,61 +55,61 @@
     insmod video_bochs
     insmod video_cirrus
   fi
 }

 terminal_output console
 if [ x$feature_timeout_style = xy ] ; then
   set timeout_style=menu
   set timeout=5
 # Fallback normal timeout code in case the timeout_style feature is
 # unavailable.
 else
   set timeout=5
 fi
 ### END /etc/grub.d/00_header ###

 ### BEGIN /etc/grub.d/10_linux ###
 menuentry 'Fedora 21 Rescue' --class fedora --class gnu-linux --class gnu --class os --unrestricted $menuentry_id_option 'gnulinux-3.15.0-0.rc5.git2.10.fc21.x86_64-advanced-a14e3dcb-ade3-42f7-832f-d9f66b5ae6a3' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos1'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  6169b46f-0257-4319-b2e4-caaed2a8e06b
        else
          search --no-floppy --fs-uuid --set=root 6169b46f-0257-4319-b2e4-caaed2a8e06b
        fi
        linuxefi /vmlinuz-0-rescue-5a94251776a14678911d4ae0949500f5 root=/fooooo ro  rd.lvm.lv=fedora_uefi/root rd.lvm.lv=fedora_uefi/swap rhgb quiet
-       initrdefi /initramfs-0-rescue-5a94251776a14678911d4ae0949500f5.img
+       initrd /initramfs-0-rescue-5a94251776a14678911d4ae0949500f5.img
 }
 menuentry 'Fedora, with Linux 3.15.0-0.rc5.git2.10.fc21.x86_64' --class fedora --class gnu-linux --class gnu --class os --unrestricted $menuentry_id_option 'gnulinux-3.15.0-0.rc5.git2.10.fc21.x86_64-advanced-a14e3dcb-ade3-42f7-832f-d9f66b5ae6a3' {
        load_video
        set gfxpayload=keep
        insmod gzio
        insmod part_msdos
        insmod ext2
        set root='hd0,msdos1'
        if [ x$feature_platform_search_hint = xy ]; then
          search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1 --hint='hd0,msdos1'  6169b46f-0257-4319-b2e4-caaed2a8e06b
        else
          search --no-floppy --fs-uuid --set=root 6169b46f-0257-4319-b2e4-caaed2a8e06b
        fi
        linuxefi /vmlinuz-3.15.0-0.rc5.git2.10.fc21.x86_64 root=/dev/mapper/fedora_uefi-root ro  rd.lvm.lv=fedora_uefi/root rd.lvm.lv=fedora_uefi/swap rhgb quiet
 }

 ### END /etc/grub.d/10_linux ###

 ### BEGIN /etc/grub.d/20_linux_xen ###

 ### END /etc/grub.d/20_linux_xen ###

 ### BEGIN /etc/grub.d/20_ppc_terminfo ###
 ### END /etc/grub.d/20_ppc_terminfo ###

 ### BEGIN /etc/grub.d/30_os-prober ###
 ### END /etc/grub.d/30_os-prober ###

 ### BEGIN /etc/grub.d/40_custom ###
 # This file provides an easy way to add custom menu entries.  Simply type the

**Comment by yangmingtai** [comment]
![image](https://user-images.githubusercontent.com/17870505/108649576-97a7cc80-74f8-11eb-86d3-f31109cec8bd.png)

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
