### ISSUE TITLE
multiple images for initrd but only the first one got recognized

### ISSUE THREAD

**Issue by dongwangdw** [rhboot/grubby#58]
I try to config a grub menuentry with grubby.

with line: initrd: /initrd.img ignition.img.

But when I try to print the config with grubby --info some_index
I found something like: 

initrd: /boot/initrd.img /ignition.img

which I expected /boot/initrd.img /boot/ignition.img.

Did I miss any thing here?

**Comment by frozencemetery** [comment]
Thank you for your interest.  We are retiring non-BLS grubby at this point and don't plan to address this.  For BLS-only grubby, please send PRs to https://src.fedoraproject.org/rpms/grubby
